### get all courses details
GET http://localhost:5000/courses

### get details of a course with ID 1390
GET http://localhost:5000/courses/121

### delete a course record with ID 1390
DELETE http://localhost:5000/courses/145

### create a new course document
POST http://localhost:5000/courses/
content-type: application/json

{
  "ID": 121,
  "name": "Rustic Fresh Shirt",
  "lectures": [
    "Timothy",
    "Zora"
  ],
  "credits": 11
}


### update course details of ID 1000
PUT http://localhost:5000/courses/121
content-type: application/json

{
  "ID": 100,
  "name": "Rustic Fresh Shirt",
  "lectures": [
    "Timothy",
    "Zora"
  ],
  "credits": 11
}


