GET http://localhost:5000/students

###
GET http://localhost:5000/students/9400

###
DELETE http://localhost:5000/students/1268

###
POST http://localhost:5000/students/
content-type: application/json

{
    "ID": 9400,
    "name": "Mariah Hariyah",
    "address": {
      "line1": "9329 Shanna Route",
      "line2": "Mahardika Center",
      "city": "West Demarcuschester"
    },
    "courseID": 145,
    "phone": "025 5262 542",
    "email": "Alfonso_Damanik@gmail.com"
  }