GET http://localhost:5000/students

###
GET http://localhost:5000/students/1390

###
DELETE http://localhost:5000/students/931

###
POST http://localhost:5000/students/
content-type: application/json

{
    "ID": 92009,
    "name": "o",
    "address": {
      "line1": "9outeppl",
      "line2": " Center",
      "city": "Westr"
    },
    "courseID": 145,
    "phone": "011 2225 112",
    "email": "asdk@gmail.com"
}


###
PUT http://localhost:5000/students/1390
content-type: application/json

{
    "address": {
      "line1": " Shasnna Route",
      "line2": "Mahardika Center",
      "line3":"Added",
      "city": "West Demarcuschester"
    }
}

