### get all students details
GET http://localhost:5000/students

### get details of a student with ID 1390
GET http://localhost:5000/students/1390

### delete a student record with ID 1390
DELETE http://localhost:5000/students/1390

### create a new student document
POST http://localhost:5000/students/
content-type: application/json

{
    "ID": 1000,
    "name": "test",
    "address": {
      "line1": "address1",
      "line2": " address2",
      "city": "city"
    },
    "courseID": 145,
    "phone": "011 2225 112",
    "email": "test@test.com"
}


### update student details of ID 1000
PUT http://localhost:5000/students/1000
content-type: application/json

{
  "name":"new name",
    "address": {
      "line3":"Added",
      "city": "West Demarcuschester"
    }
}

